


# - name: Checking {{current_feature.kind}}
#   debug:
#     var: current_feature




- name: 🚀 LOOP OVER PRODUCT FEATURES
  debug: 
    msg: 
    - "***************************************************************************************************************************************************"
    - "***************************************************************************************************************************************************"
    - "                                                                                                                                                   "
    - "       🟣🟣🟣🟣🟣🟣🟣🟢🟢🟢 IBM IT Automation - INSTALLATION -  LOOP OVER PRODUCT FEATURES                                                                    "
    - "                                                                                                                                                   "
    - "***************************************************************************************************************************************************"


- name: 🟣  Show Current Feature
  debug:
    var: current_feature
    verbosity: 1




- name: tools-install-modules-loop 🌡   CHECK for - IBM Concert Operate
  include_role:
    name: ibm-concert-operate-install
  when: current_feature.kind=="IBMConcertOperate" and current_feature.install|bool == true


- name: tools-install-modules-loop 🌡   CHECK for - IBM Concert Operate Demo Content
  include_role:
    name: ibm-concert-operate-demo-content
  when: current_feature.kind=="IBMConcertOperateDemoContent" and current_feature.install|bool == true



- name: tools-install-modules-loop 🌡   CHECK for - IBM EventManager
  include_role:
    name: ibm-event-manager-install
  when: current_feature.kind=="EventManager" and current_feature.install|bool == true


- name: tools-install-modules-loop 🌡   CHECK for - IBM EventManager Demo Content
  include_role:
    name: ibm-event-manager-demo-content
  when: current_feature.kind=="EventManagerDemoContent" and current_feature.install|bool == true




- name: tools-install-modules-loop 🌡   CHECK for - IBM Concert Platform
  include_role:
    name: ibm-concert-platform-install
  when: current_feature.kind=="IBMConcertPlatform" and current_feature.install|bool == true


- name: tools-install-modules-loop 🌡   CHECK for - IBM Concert Platform Demo Content
  include_role:
    name: ibm-concert-platform-demo-content
  when: current_feature.kind=="IBMConcertPlatformDemoContent" and current_feature.install|bool == true



- name: tools-install-modules-loop 🌡   CHECK for - IBM Instana
  include_role:
    name: ibm-instana-install
  when: current_feature.kind=="IBMInstana" and current_feature.install|bool == true

- name: tools-install-modules-loop 🌡   CHECK for - IBM Instana Demo Content
  include_role:
    name: ibm-instana-demo-content
  when: current_feature.kind=="IBMInstanaDemoContent" and current_feature.install|bool == true



- name: tools-install-modules-loop 🌡   CHECK for - IBM Concert Optimise
  include_role:
    name: ibm-concert-optimise-install
  when: current_feature.kind=="IBMConcertOptimise" and current_feature.install|bool == true

- name: tools-install-modules-loop 🌡   CHECK for - IBM Concert Optimise Demo Content
  include_role:
    name: ibm-concert-optimise-demo-content
  when: current_feature.kind=="IBMConcertOptimiseDemoContent" and current_feature.install|bool == true



