---
apiVersion: v1                     
kind: Namespace
metadata:
  name: ibm-demo-ui
---  
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibm-demo-ui-admin
  namespace: ibm-demo-ui
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-demo-ui-admin-crb
subjects:
  - kind: ServiceAccount
    name: ibm-demo-ui-admin
    namespace: ibm-demo-ui
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  ibm-demo-ui-config
  namespace: ibm-demo-ui
data:
  TOKEN: CHANGEME
  INSTANCE_NAME: Dexter

  DEMO_USER: "demo"
  DEMO_PWD: "CHANGEME"

  ADMIN_MODE: "true"
  GET_CONFIG: "true"

  CONTACT_INFO: '<p style="font-size:40px;">Contacts</p><BR><p>Niklaus Hirt - nikh@ch.ibm.com</p><p></p>'

  ENV_CMD: "export OCP_URL=$(oc get Infrastructure cluster -o jsonpath={.status.apiServerURL})\nexport OCP_TOKEN=$(oc create token -n ibm-installer ibm-installer-admin --duration=999999999s)\n\necho \"------------------------------------------------------------------------------------------------------------------------------<BR>\"\necho \" ✅ LOGINS FOR RESILIENCE<BR>\"\necho \"------------------------------------------------------------------------------------------------------------------------------<BR>\"\nexport API_TOKEN=$(oc create token -n default demo-admin-concert --duration=999999999s)\n\nexport CONSOLE_PATH=$(oc get route -n openshift-console console -o jsonpath={.spec.host})\nexport CONSOLE_URL=\"https://\"$CONSOLE_PATH\nexport API_URL=\"https://api${CONSOLE_PATH#console-openshift-console}:6443\"\n\necho \"<BR>\"\necho \"  \U0001F30F API URL  :   $OCP_URL<BR>\"\necho \"  \U0001F510 API TOKEN:   $OCP_TOKEN\"\n\necho \"<BR>\"\necho \"<BR>\"\n\n\n\n\necho \"------------------------------------------------------------------------------------------------------------------------------<BR>\"\necho \" ✅ CHECK WATSONX CREDENTIALS<BR>\"\necho \"------------------------------------------------------------------------------------------------------------------------------<BR>\"\nCONCERT_NAMESPACE=$(oc get po -A|grep roja-portal |awk '{print$1}')\n\nAPI_KEY=\"$(oc get secret app-cfg-secret -n $CONCERT_NAMESPACE -o jsonpath='{ .data.WATSONX_API_KEY }' | base64 --decode)\"\n\n\nRESPONSE=$(curl -s -X POST https://iam.cloud.ibm.com/identity/token -H \"Content-Type: application/x-www-form-urlencoded\" -d \"grant_type=urn:ibm:params:oauth:grant-type:apikey&apikey=$API_KEY\")\n\n#echo \"$RESPONSE\" | jq\n\nif echo \"$RESPONSE\" | jq -e '.errorMessage' > /dev/null 2>&1; then\necho \"<BR>\"\necho \"    \U0001F534\U0001F534\U0001F534\U0001F534\U0001F534\U0001F534 WATSONX TOKEN INVALID - Error returned from IAM. You won't be able to access the WatsonX services in Concert platform.<BR>\"\necho \"\"\nexit 1\nelse\necho \"<BR>\"\necho \"    ✅ Successfully retrieved IAM token. You can access the WatsonX services in Concert platform.<BR>\"\necho \"<BR>\"\nfi\n\n\necho \"------------------------------------------------------------------------------------------------------------------------------<BR>\"\necho \" ✅ LDAP CREDENTIALS<BR>\"\necho \"------------------------------------------------------------------------------------------------------------------------------<BR>\"\n\necho \"id\": \"LDAP<BR>\"\necho \"realm\": \"REALM<BR>\"\necho \"url\": \"ldap://openldap.openldap:389<BR>\"\necho \"host\": \"openldap.openldap<BR>\"\necho \"port\": \"389<BR>\"\necho \"protocol\": \"ldap<BR>\"\necho \"basedn\": \"dc=ibm,dc=com<BR>\"\necho \"binddn\": \"cn=admin,dc=ibm,dc=com<BR>\"\necho \"bindpassword: The one you selected at installation time<BR>\"\necho \"type\": \"Custom<BR>\"\necho \"ignorecase\": \"false<BR>\"\necho \"userfilter\": \"(&(uid=%v)(objectclass=Person))<BR>\"\necho \"useridmap\": \"*:uid<BR>\"\necho \"groupfilter\": \"(&(cn=%v)(objectclass=groupOfUniqueNames))<BR>\"\necho \"groupidmap\": \"*:cn<BR>\"\necho \"groupmemberidmap\": \"groupOfUniqueNames:uniqueMember<BR>\"\necho \"nestedsearch\": \"false<BR>\"\necho \"pagingsearch\": \"false<BR>\"\nexport openldap_app_route=$(oc get route -n openldap admin -o jsonpath={.spec.host})          \necho \"openldap_app_route:     https://$openldap_app_route<BR>\""
